version: "3.8"
services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    restart: always
    user: root                                # run as root to avoid permission issues
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Admin@123  
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      #- SPLUNK_HEC_TOKEN=add_this_after_creating
      # Note: SPLUNK_HEC_TOKEN does NOT auto-create HEC token in Splunk
    ports:
      - "8000:8000"   # UI
      - "8088:8088"   # HEC
      - "8089:8089"   # mgmt (REST API)
      - "9997:9997"   # Forwarder port
    volumes:
      - splunk-data:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc

volumes:
  splunk-data:
  splunk-etc:


