version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: tm_mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql-db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask:
    build: ./flask-dashboard
    container_name: tm_flask
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./flask-dashboard:/app:rw
      - ./splunk-ca.pem:/etc/ssl/certs/splunk-ca.pem:ro   # <-- mounted Splunk CA cert
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  nginx:
    build: ./nginx-frontend
    container_name: tm_nginx
    restart: unless-stopped
    depends_on:
      - flask
    ports:
      - "8080:80"
    volumes:
      - ./nginx-frontend/static:/usr/share/nginx/html:ro
      - ./nginx-frontend/nginx.conf:/etc/nginx/nginx.conf:ro

  splunk:
    image: splunk/splunk:8.2.0
    container_name: tm_splunk
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_ADMIN_PASSWORD}
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
    ports:
      - "8000:8000"   # Splunk web
      - "8088:8088"   # HEC
    volumes:
      - splunk_data:/opt/splunk/var
      - ./K8s/splunk-local-etc:/opt/splunk/etc:rw
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/en-US/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 6

  redis:
    image: redis:7-alpine
    container_name: tm_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  splunk_data:

